services:

  # ubuntu 20 ros1
  u20_cuda_r1:
    build:
      context: ./docker_build
      dockerfile: u20/cuda/ros1/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu20.04:${PACKAGE_VERSION}-cnvros1
    container_name:
      u20_cuda_r1
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  u20_cuda_runtime_r1:
    build:
      context: ./docker_build
      dockerfile: u20/cuda_runtime/ros1/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu20.04:${PACKAGE_VERSION}-cnvros1-runtime
    container_name:
      u20_cuda_runtime_r1
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  u20_non_nvidia_r1:
    build:
      context: ./docker_build
      dockerfile: u20/non_nvidia/ros1/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu20.04:${PACKAGE_VERSION}-ros1
    container_name:
      u20_non_nvidia_r1
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  # ubuntu 20 ros2
  u20_cuda_r2:
    build:
      context: ./docker_build
      dockerfile: u20/cuda/ros2/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu20.04:${PACKAGE_VERSION}-cnvros2
    container_name:
      u24_non_nvidia
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  u20_cuda_runtime_r2:
    build:
      context: ./docker_build
      dockerfile: u20/cuda_runtime/ros2/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu20.04:${PACKAGE_VERSION}-cnvros2-runtime
    container_name:
      u20_cuda_runtime_r2
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  u20_non_nvidia_r2:
    build:
      context: ./docker_build
      dockerfile: u20/non_nvidia/ros2/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu20.04:${PACKAGE_VERSION}-ros2
    container_name:
      u20_non_nvidia_r2
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  # ubuntu 20 ros3
  u20_cuda_r3:
    build:
      context: ./docker_build
      dockerfile: u20/cuda/ros3/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu20.04:${PACKAGE_VERSION}-cnvros3
    container_name:
      u20_cuda_r3
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  u20_cuda_runtime_r3:
    build:
      context: ./docker_build
      dockerfile: u20/cuda_runtime/ros3/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu20.04:${PACKAGE_VERSION}-cnvros3-runtime
    container_name:
      u20_cuda_runtime_r3
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  u20_non_nvidia_r3:
    build:
      context: ./docker_build
      dockerfile: u20/non_nvidia/ros3/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu20.04:${PACKAGE_VERSION}-ros3
    container_name:
      u20_non_nvidia_r3
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  # ubuntu 22 ros2
  u22_cuda:
    build:
      context: ./docker_build
      dockerfile: u22/cuda/ros2/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu22.04:${PACKAGE_VERSION}-cnvros2
    container_name:
      u22_cuda
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  u22_cuda_runtime:
    build:
      context: ./docker_build
      dockerfile: u22/cuda_runtime/ros2/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu22.04:${PACKAGE_VERSION}-cnvros2-runtime
    container_name:
      u22_cuda_runtime
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  u22_non_nvidia:
    build:
      context: ./docker_build
      dockerfile: u22/non_nvidia/ros2/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu22.04:${PACKAGE_VERSION}-ros2
    container_name:
      u22_non_nvidia
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  # ubuntu 24 ros2
  u24_cuda:
    build:
      context: ./docker_build
      dockerfile: u24/cuda/ros2/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu24.04:${PACKAGE_VERSION}-cnvros2
    container_name:
      u24_cuda
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  u24_cuda_runtime:
    build:
      context: ./docker_build
      dockerfile: u24/cuda_runtime/ros2/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu24.04:${PACKAGE_VERSION}-cnvros2-runtime
    container_name:
      u24_cuda_runtime
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

  u24_non_nvidia:
    build:
      context: ./docker_build
      dockerfile: u24/non_nvidia/ros2/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu24.04:${PACKAGE_VERSION}-ros2
    container_name:
      u24_non_nvidia
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - WAYLAND_DISPLAY=/tmp/${WAYLAND_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /media:/media
      - ./docker_mount:/home/developer/docker_mount
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}
