services:
  cuda:
    build:
      context: ./docker_build
      dockerfile: u${UBUNTU_VERSION}/cuda/ros${ROS_VERSION}/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu${UBUNTU_VERSION}.04:${PACKAGE_VERSION}-cnvros${ROS_VERSION}
    profiles:
      - all
      - cuda

  cuda_runtime:
    build:
      context: ./docker_build
      dockerfile: u${UBUNTU_VERSION}/cuda_runtime/ros${ROS_VERSION}/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu${UBUNTU_VERSION}.04:${PACKAGE_VERSION}-cnvros2-runtime
    profiles:
      - all
      - cuda_runtime

  non_nvidia:
    build:
      context: ./docker_build
      dockerfile: u${UBUNTU_VERSION}/non_nvidia/ros${ROS_VERSION}/Dockerfile
      args:
        user_id: ${user_id}
    image:
      ubuntu${UBUNTU_VERSION}.04:${PACKAGE_VERSION}-ros${ROS_VERSION}
    profiles:
      - all
      - non_nvidia
