name: U18 ROS1 Docker Image CI (opengl)

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker_build/u18/opengl/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for U18 ROS1 (opengl)
      run: docker build --rm -t test_image --build-arg user_id=$(id -u) -f docker_build/u18/opengl/Dockerfile .
