name: U20 ROS2 Docker Image CI (non nvidia)

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker_build/u20/non_nvidia/ros2/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for U20 ROS2 (non nvidia)
      run: docker build --rm -t ubuntu20.04:ros --build-arg user_id=$(id -u) -f docker_build/u20/non_nvidia/ros2/Dockerfile .
