name: U22 ROS2 Docker Image CI (cuda runtime)

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker_build/u22/cuda_runtime/ros2/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for U22 ROS2 (cuda runtime)
      run: docker build --rm -t ubuntu22.04:v0.0.3-cnvros2-runtime --build-arg user_id=$(id -u) -f docker_build/u22/cuda_runtime/ros2/Dockerfile .
