name: U22 ROS2 Docker Image CI (opengl)

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker_build/u22/cudagl/ros2/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for U22 ROS2 (opengl)
      run: docker build --rm -t ubuntu22.04:ros2 --build-arg user_id=$(id -u) -f docker_build/u22/cudagl/ros2/Dockerfile .
