name: U24 ROS2 Docker Image CI (cuda)

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker_build/u24/cuda/ros2/**'

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      UBUNTU_VERSION: "24"
      PACKAGE_VERSION: "v0.0.3"

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for U24 ROS2 (cuda)
      run: docker build --rm -t ubuntu$UBUNTU_VERSION.04:$PACKAGE_VERSION-cnvros2--build-arg user_id=$(id -u) -f docker_build/u$UBUNTU_VERSION/cuda/ros$ROS_VERSION/Dockerfile .
