name: U24 ROS2 Docker Image CI (cuda)

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker_build/u24/cuda/ros2/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for U24 ROS2 (cuda)
      run: docker build --rm -t ubuntu24.04:v0.0.3-cnvros2 --build-arg user_id=$(id -u) -f docker_build/u24/cuda/ros2/Dockerfile .
